/* eslint-disable @typescript-eslint/no-empty-object-type */
// data/productCollections.ts
export interface Product {
  id: string;
  img: string;
  name: string;
  brand: string;
  price: string;
  images: string[];
  sales: number; // total sales count
  reviewsCount: number; // number of reviews
  rating: number; // average rating out of 5
  description: string;
  features: string[];
}
type NewProduct = {
  id: number;
  path: string;
  categories: string[];
  img: string;
  name: string;
  price: string;
  reviews: string;
  soldOutText?: string;
  brand?: string;
  images?: string[];
  sales?: number;
  reviewsCount?: number;
  rating?: number;
  description?: string;
  features?: string[];
};

export const jacketProducts: Product[] = [
  {
    id: "1",
    img: "/jacket/Picture62.png",
    name: "Cat Taiyaki Tee",
    brand: "Al Karam",
    price: "95.5",
    images: [
      "/jacket/Picture62.png",
      "/jacket/Picture63.png",
      "/jacket/Picture64.png",
    ],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description:
      "Embrace your love for cats and sweet treats with the Cat Taiyaki Tee! This fun and quirky T-shirt features an adorable design of a playful cat enjoying a taiyaki, the iconic fish-shaped Japanese dessert. Made from premium-quality cotton, it offers a soft, breathable, and comfortable fit perfect for everyday wear.",
    features: [
      "Material: 100% high-quality cotton",
      "Fit: Relaxed and unisex sizing",
      "Design: Durable, fade-resistant cat and taiyaki graphic",
      "Perfect for casual outings, cozy days, or gifting to fellow cat enthusiasts",
    ],
  },
  {
    id: "2",
    img: "/jacket/Picture63.png",
    name: "Cat Taiyaki Tee",
    brand: "Al Karam",
    price: "95.5",
    images: [
      "/jacket/Picture62.png",
      "/jacket/Picture63.png",
      "/jacket/Picture64.png",
    ],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description:
      "Embrace your love for cats and sweet treats with the Cat Taiyaki Tee! This fun and quirky T-shirt features an adorable design of a playful cat enjoying a taiyaki, the iconic fish-shaped Japanese dessert. Made from premium-quality cotton, it offers a soft, breathable, and comfortable fit perfect for everyday wear.",
    features: [
      "Material: 100% high-quality cotton",
      "Fit: Relaxed and unisex sizing",
      "Design: Durable, fade-resistant cat and taiyaki graphic",
      "Perfect for casual outings, cozy days, or gifting to fellow cat enthusiasts",
    ],
  },
  {
    id: "3",
    img: "/jacket/Picture64.png",
    name: "Cat Taiyaki Tee",
    brand: "Al Karam",
    price: "95.5",
    images: [
      "/jacket/Picture62.png",
      "/jacket/Picture63.png",
      "/jacket/Picture64.png",
    ],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description:
      "Embrace your love for cats and sweet treats with the Cat Taiyaki Tee! This fun and quirky T-shirt features an adorable design of a playful cat enjoying a taiyaki, the iconic fish-shaped Japanese dessert. Made from premium-quality cotton, it offers a soft, breathable, and comfortable fit perfect for everyday wear.",
    features: [
      "Material: 100% high-quality cotton",
      "Fit: Relaxed and unisex sizing",
      "Design: Durable, fade-resistant cat and taiyaki graphic",
      "Perfect for casual outings, cozy days, or gifting to fellow cat enthusiasts",
    ],
  },
];

export const bagProducts: Product[] = [
  {
    id: "1",
    img: "/bag/Picture10.png",
    name: "bag",
    brand: "Al Karam",
    price: "95.5",
    images: ["/bag/Picture65.png", "/bag/Picture66.png", "/bag/Picture67.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description:
      "Embrace your love for cats and sweet treats with the Cat Taiyaki Tee! This fun and quirky T-shirt features an adorable design of a playful cat enjoying a taiyaki, the iconic fish-shaped Japanese dessert. Made from premium-quality cotton, it offers a soft, breathable, and comfortable fit perfect for everyday wear.",
    features: [
      "Material: 100% high-quality cotton",
      "Fit: Relaxed and unisex sizing",
      "Design: Durable, fade-resistant cat and taiyaki graphic",
      "Perfect for casual outings, cozy days, or gifting to fellow cat enthusiasts",
    ],
  },
  {
    id: "2",
    img: "/bag/Picture65.png",
    name: "bag",
    brand: "Al Karam",
    price: "95.5",
    images: ["/bag/Picture65.png", "/bag/Picture66.png", "/bag/Picture67.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description:
      "Embrace your love for cats and sweet treats with the Cat Taiyaki Tee! This fun and quirky T-shirt features an adorable design of a playful cat enjoying a taiyaki, the iconic fish-shaped Japanese dessert. Made from premium-quality cotton, it offers a soft, breathable, and comfortable fit perfect for everyday wear.",
    features: [
      "Material: 100% high-quality cotton",
      "Fit: Relaxed and unisex sizing",
      "Design: Durable, fade-resistant cat and taiyaki graphic",
      "Perfect for casual outings, cozy days, or gifting to fellow cat enthusiasts",
    ],
  },
  {
    id: "3",
    img: "/bag/Picture66.png",
    name: "bag",
    brand: "Al Karam",
    price: "95.5",
    images: ["/bag/Picture65.png", "/bag/Picture66.png", "/bag/Picture67.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description:
      "Embrace your love for cats and sweet treats with the Cat Taiyaki Tee! This fun and quirky T-shirt features an adorable design of a playful cat enjoying a taiyaki, the iconic fish-shaped Japanese dessert. Made from premium-quality cotton, it offers a soft, breathable, and comfortable fit perfect for everyday wear.",
    features: [
      "Material: 100% high-quality cotton",
      "Fit: Relaxed and unisex sizing",
      "Design: Durable, fade-resistant cat and taiyaki graphic",
      "Perfect for casual outings, cozy days, or gifting to fellow cat enthusiasts",
    ],
  },
  {
    id: "4",
    img: "/bag/Picture67.png",
    name: "bag",
    brand: "Al Karam",
    price: "95.5",
    images: ["/bag/Picture65.png", "/bag/Picture66.png", "/bag/Picture67.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description:
      "Embrace your love for cats and sweet treats with the Cat Taiyaki Tee! This fun and quirky T-shirt features an adorable design of a playful cat enjoying a taiyaki, the iconic fish-shaped Japanese dessert. Made from premium-quality cotton, it offers a soft, breathable, and comfortable fit perfect for everyday wear.",
    features: [
      "Material: 100% high-quality cotton",
      "Fit: Relaxed and unisex sizing",
      "Design: Durable, fade-resistant cat and taiyaki graphic",
      "Perfect for casual outings, cozy days, or gifting to fellow cat enthusiasts",
    ],
  },
  {
    id: "5",
    img: "/bag/Picture68.png",
    name: "bag",
    brand: "Al Karam",
    price: "95.5",
    images: ["/bag/Picture65.png", "/bag/Picture66.png", "/bag/Picture67.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description:
      "Embrace your love for cats and sweet treats with the Cat Taiyaki Tee! This fun and quirky T-shirt features an adorable design of a playful cat enjoying a taiyaki, the iconic fish-shaped Japanese dessert. Made from premium-quality cotton, it offers a soft, breathable, and comfortable fit perfect for everyday wear.",
    features: [
      "Material: 100% high-quality cotton",
      "Fit: Relaxed and unisex sizing",
      "Design: Durable, fade-resistant cat and taiyaki graphic",
      "Perfect for casual outings, cozy days, or gifting to fellow cat enthusiasts",
    ],
  },
  {
    id: "6",
    img: "/bag/Picture69.png",
    name: "bag",
    brand: "Al Karam",
    price: "95.5",
    images: ["/bag/Picture65.png", "/bag/Picture66.png", "/bag/Picture67.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description:
      "Embrace your love for cats and sweet treats with the Cat Taiyaki Tee! This fun and quirky T-shirt features an adorable design of a playful cat enjoying a taiyaki, the iconic fish-shaped Japanese dessert. Made from premium-quality cotton, it offers a soft, breathable, and comfortable fit perfect for everyday wear.",
    features: [
      "Material: 100% high-quality cotton",
      "Fit: Relaxed and unisex sizing",
      "Design: Durable, fade-resistant cat and taiyaki graphic",
      "Perfect for casual outings, cozy days, or gifting to fellow cat enthusiasts",
    ],
  },
];

export const footwearProducts: Product[] = [
  {
    id: "1",
    img: "/footwear/Picture2.png",
    name: "Upper: Cow Alpha Dior",
    brand: "Outsole: HANDMADE",
    price: "24.00",
    images: ["/footwear/Picture2.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "Available Immediately",
    features: [
      "Material: 100% high-quality cotton",
      "Fit: Relaxed and unisex sizing",
      "Design: Durable, fade-resistant cat and taiyaki graphic",
      "Perfect for casual outings, cozy days, or gifting to fellow cat enthusiasts",
      "40 HQ container can fit 6000 PAIRS",
    ],
  },
  {
    id: "2",
    img: "/footwear/Picture3.png",
    name: "Upper: Cow Maurica Tan",
    brand: "Outsole: HANDMADE",
    price: "24.50",
    images: ["/footwear/Picture3.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "Available Immediately",
    features: [
      "All these styles in production",
      "Tentative delivery in 75-80 days",
      "All styles available in SIZEs 7-13",
      "MOQ - 500 pairs/ color and 1000 pairs/ style",
      "40 HQ container can fit 6000 PAIRS",
    ],
  },
  {
    id: "3",
    img: "/footwear/Picture4.png",
    name: "Upper: Cow Maurica Tan",
    brand: "Outsole: HANDMADE",
    price: "27.50",
    images: ["/footwear/Picture4.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "Available Immediately",
    features: [
      "All these styles in production",
      "Tentative delivery in 75-80 days",
      "All styles available in SIZEs 7-13",
      "MOQ - 500 pairs/ color and 1000 pairs/ style",
      "40 HQ container can fit 6000 PAIRS",
    ],
  },
  {
    id: "4",
    img: "/footwear/Picture5.png",
    name: "Upper: Cow Alpha Dior (Nappa)",
    brand: "Outsole: HANDMADE",
    price: "27.50",
    images: ["/footwear/Picture5.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "Available Immediately",
    features: [
      "All these styles in production",
      "Tentative delivery in 75-80 days",
      "All styles available in SIZEs 7-13",
      "MOQ - 500 pairs/ color and 1000 pairs/ style",
      "40 HQ container can fit 6000 PAIRS",
    ],
  },
  {
    id: "5",
    img: "/footwear/Picture6.png",
    name: "Upper: Cow Maurica Tan",
    brand: "Outsole: TPR",
    price: "28.00",
    images: ["/footwear/Picture6.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "Available Immediately",
    features: [
      "All these styles in production",
      "Tentative delivery in 75-80 days",
      "All styles available in SIZEs 7-13",
      "MOQ - 500 pairs/ color and 1000 pairs/ style",
      "40 HQ container can fit 6000 PAIRS",
    ],
  },
  {
    id: "1",
    img: "/footwear/Picture40.png",
    name: "LAST-OUTBACK",
    brand: "",
    price: "25.00",
    images: ["/footwear/Picture40.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "",
    features: [],
  },
  {
    id: "2",
    img: "/footwear/Picture41.png",
    name: "LAST-LAUREN (STUDDED BOOT)",
    brand: "",
    price: "25.00",
    images: ["/footwear/Picture41.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "",
    features: [],
  },
  {
    id: "3",
    img: "/footwear/Picture42.png",
    name: "BUCKLED BOOT",
    brand: "",
    price: "26.00",
    images: ["/footwear/Picture42.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "",
    features: [],
  },
  {
    id: "4",
    img: "/footwear/Picture43.png",
    name: "LACE UP BOOT",
    brand: "",
    price: "33.00",
    images: ["/footwear/Picture43.png", "/footwear/Picture45.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "",
    features: [],
  },
  {
    id: "5",
    img: "/footwear/Picture46.png",
    name: "LACE UP ANKLE BOOT",
    brand: "",
    price: "25.00",
    images: ["/footwear/Picture46.png", "/footwear/Picture47.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "",
    features: [],
  },
];
export const menFootwearProducts: Product[] = [
  {
    id: "1",
    img: "/footwear/Picture2.png",
    name: "Upper: Cow Alpha Dior",
    brand: "Outsole: HANDMADE",
    price: "24.00",
    images: ["/footwear/Picture2.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "Available Immediately",
    features: [
      "Material: 100% high-quality cotton",
      "Fit: Relaxed and unisex sizing",
      "Design: Durable, fade-resistant cat and taiyaki graphic",
      "Perfect for casual outings, cozy days, or gifting to fellow cat enthusiasts",
      "40 HQ container can fit 6000 PAIRS",
    ],
  },
  {
    id: "2",
    img: "/footwear/Picture3.png",
    name: "Upper: Cow Maurica Tan",
    brand: "Outsole: HANDMADE",
    price: "24.50",
    images: ["/footwear/Picture3.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "Available Immediately",
    features: [
      "All these styles in production",
      "Tentative delivery in 75-80 days",
      "All styles available in SIZEs 7-13",
      "MOQ - 500 pairs/ color and 1000 pairs/ style",
      "40 HQ container can fit 6000 PAIRS",
    ],
  },
  {
    id: "3",
    img: "/footwear/Picture4.png",
    name: "Upper: Cow Maurica Tan",
    brand: "Outsole: HANDMADE",
    price: "27.50",
    images: ["/footwear/Picture4.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "Available Immediately",
    features: [
      "All these styles in production",
      "Tentative delivery in 75-80 days",
      "All styles available in SIZEs 7-13",
      "MOQ - 500 pairs/ color and 1000 pairs/ style",
      "40 HQ container can fit 6000 PAIRS",
    ],
  },
  {
    id: "4",
    img: "/footwear/Picture5.png",
    name: "Upper: Cow Alpha Dior (Nappa)",
    brand: "Outsole: HANDMADE",
    price: "27.50",
    images: ["/footwear/Picture5.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "Available Immediately",
    features: [
      "All these styles in production",
      "Tentative delivery in 75-80 days",
      "All styles available in SIZEs 7-13",
      "MOQ - 500 pairs/ color and 1000 pairs/ style",
      "40 HQ container can fit 6000 PAIRS",
    ],
  },
  {
    id: "5",
    img: "/footwear/Picture6.png",
    name: "Upper: Cow Maurica Tan",
    brand: "Outsole: TPR",
    price: "28.00",
    images: ["/footwear/Picture6.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "Available Immediately",
    features: [
      "All these styles in production",
      "Tentative delivery in 75-80 days",
      "All styles available in SIZEs 7-13",
      "MOQ - 500 pairs/ color and 1000 pairs/ style",
      "40 HQ container can fit 6000 PAIRS",
    ],
  },
  {
    id: "6",
    img: "/footwear/Picture7.png",
    name: "Upper: Cow Maurica Tan",
    brand: "Outsole: TPR",
    price: "25.00",
    images: ["/footwear/Picture7.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "",
    features: [
      "All these styles in production",
      "Tentative delivery in 75-80 days",
      "All styles available in SIZEs 7-13",
      "MOQ - 500 pairs/ color and 1000 pairs/ style",
      "40 HQ container can fit 6000 PAIRS",
    ],
  },
  {
    id: "7",
    img: "/footwear/Picture8.png",
    name: "Upper: Cow Maurica Brown",
    brand: "Outsole: Handmade",
    price: "28.00",
    images: ["/footwear/Picture8.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "",
    features: [
      "All these styles in production",
      "Tentative delivery in 75-80 days",
      "All styles available in SIZEs 7-13",
      "MOQ - 500 pairs/ color and 1000 pairs/ style",
      "40 HQ container can fit 6000 PAIRS",
    ],
  },
  {
    id: "8",
    img: "/footwear/Picture8.png",
    name: "Upper: Cow Maurica Brown",
    brand: "Outsole: Handmade",
    price: "28.00",
    images: ["/footwear/Picture8.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "",
    features: [
      "All these styles in production",
      "Tentative delivery in 75-80 days",
      "All styles available in SIZEs 7-13",
      "MOQ - 500 pairs/ color and 1000 pairs/ style",
      "40 HQ container can fit 6000 PAIRS",
    ],
  },
  {
    id: "9",
    img: "/footwear/Picture10.png",
    name: "12238",
    brand: "",
    price: "24.00",
    images: ["/footwear/Picture10.png", "/footwear/Picture11.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "",
    features: [],
  },
  {
    id: "10",
    img: "/footwear/Picture12.png",
    name: "12254",
    brand: "",
    price: "25.50",
    images: ["/footwear/Picture12.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "",
    features: [],
  },
  {
    id: "11",
    img: "/footwear/Picture13.png",
    name: "12260",
    brand: "",
    price: "25.00",
    images: ["/footwear/Picture13.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "",
    features: [],
  },
  {
    id: "12",
    img: "/footwear/Picture14.png",
    name: "12235",
    brand: "",
    price: "24.00",
    images: ["/footwear/Picture14.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "",
    features: [],
  },
  {
    id: "13",
    img: "/footwear/Picture15.png",
    name: "DRESS-1",
    brand: "",
    price: "24.00",
    images: ["/footwear/Picture15.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "",
    features: [],
  },
  {
    id: "14",
    img: "/footwear/Picture16.png",
    name: "DRESS-2",
    brand: "",
    price: "24.00",
    images: ["/footwear/Picture16.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "",
    features: [],
  },
  {
    id: "15",
    img: "/footwear/Picture17.png",
    name: "12069",
    brand: "",
    price: "25.00",
    images: ["/footwear/Picture17.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "",
    features: [],
  },
  {
    id: "16",
    img: "/footwear/Picture18.png",
    name: "COLOGNE-2",
    brand: "",
    price: "25.00",
    images: ["/footwear/Picture18.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "",
    features: [],
  },
  {
    id: "17",
    img: "/footwear/Picture19.png",
    name: "11677 (CANVAS)",
    brand: "",
    price: "20.00",
    images: ["/footwear/Picture19.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "",
    features: [],
  },
  {
    id: "18",
    img: "/footwear/Picture20.png",
    name: "12194",
    brand: "",
    price: "26.00",
    images: ["/footwear/Picture20.png", "/footwear/Picture21.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "",
    features: [],
  },
  {
    id: "19",
    img: "/footwear/Picture22.png",
    name: "12249",
    brand: "",
    price: "27.00",
    images: ["/footwear/Picture22.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "",
    features: [],
  },
  {
    id: "20",
    img: "/footwear/Picture23.png",
    name: "12252",
    brand: "",
    price: "27.50",
    images: ["/footwear/Picture23.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "",
    features: [],
  },
  {
    id: "21",
    img: "/footwear/Picture24.png",
    name: "12242",
    brand: "",
    price: "27.00",
    images: ["/footwear/Picture24.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "",
    features: [],
  },
  {
    id: "22",
    img: "/footwear/Picture25.png",
    name: "12251",
    brand: "",
    price: "28.00",
    images: ["/footwear/Picture25.png", "/footwear/Picture26.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "",
    features: [],
  },
  {
    id: "23",
    img: "/footwear/Picture27.png",
    name: "12223",
    brand: "",
    price: "27.50",
    images: ["/footwear/Picture27.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "",
    features: [],
  },
  {
    id: "24",
    img: "/footwear/Picture28.png",
    name: "LACE UP BOOT",
    brand: "",
    price: "27.00",
    images: ["/footwear/Picture28.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "",
    features: [],
  },
  {
    id: "25",
    img: "/footwear/Picture29.png",
    name: "11876 BROWN",
    brand: "",
    price: "28.50",
    images: ["/footwear/Picture29.png", "/footwear/Picture30.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "",
    features: [],
  },
  {
    id: "26",
    img: "/footwear/Picture31.png",
    name: "11876( SUEDE AND CRUNCH)",
    brand: "",
    price: "28.50",
    images: ["/footwear/Picture31.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "",
    features: [],
  },
  {
    id: "27",
    img: "/footwear/Picture32.png",
    name: "1709",
    brand: "",
    price: "28.00",
    images: ["/footwear/Picture32.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "",
    features: [],
  },
  {
    id: "28",
    img: "/footwear/Picture33.png",
    name: "LS 1692",
    brand: "",
    price: "26.00",
    images: ["/footwear/Picture33.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "",
    features: [],
  },
  {
    id: "29",
    img: "/footwear/Picture34.png",
    name: "1691",
    brand: "",
    price: "27.00",
    images: ["/footwear/Picture34.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "",
    features: [],
  },
  {
    id: "30",
    img: "/footwear/Picture35.png",
    name: "1707",
    brand: "",
    price: "27.00",
    images: ["/footwear/Picture35.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "",
    features: [],
  },
  {
    id: "31",
    img: "/footwear/Picture36.png",
    name: "1689",
    brand: "",
    price: "27.00",
    images: ["/footwear/Picture36.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "",
    features: [],
  },
  {
    id: "32",
    img: "/footwear/Picture37.png",
    name: "11624 (DESERT BOOT)",
    brand: "",
    price: "22.00",
    images: ["/footwear/Picture37.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "Best Seller ",
    features: [],
  },
  {
    id: "33",
    img: "/footwear/Picture38.png",
    name: "11857",
    brand: "",
    price: "27.00",
    images: ["/footwear/Picture38.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "Best Seller ",
    features: [],
  },
  {
    id: "34",
    img: "/footwear/Picture39.png",
    name: "11571",
    brand: "",
    price: "26.00",
    images: ["/footwear/Picture39.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "Best Seller ",
    features: [],
  },
];
export const womenFootwearProducts: Product[] = [
  {
    id: "1",
    img: "/footwear/Picture40.png",
    name: "LAST-OUTBACK",
    brand: "",
    price: "25.00",
    images: ["/footwear/Picture40.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "",
    features: [],
  },
  {
    id: "2",
    img: "/footwear/Picture41.png",
    name: "LAST-LAUREN (STUDDED BOOT)",
    brand: "",
    price: "25.00",
    images: ["/footwear/Picture41.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "",
    features: [],
  },
  {
    id: "3",
    img: "/footwear/Picture42.png",
    name: "BUCKLED BOOT",
    brand: "",
    price: "26.00",
    images: ["/footwear/Picture42.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "",
    features: [],
  },
  {
    id: "4",
    img: "/footwear/Picture43.png",
    name: "LACE UP BOOT",
    brand: "",
    price: "33.00",
    images: ["/footwear/Picture43.png", "/footwear/Picture45.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "",
    features: [],
  },
  {
    id: "5",
    img: "/footwear/Picture46.png",
    name: "LACE UP ANKLE BOOT",
    brand: "",
    price: "25.00",
    images: ["/footwear/Picture46.png", "/footwear/Picture47.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "",
    features: [],
  },
  {
    id: "6",
    img: "/footwear/Picture48.png",
    name: "LAST-LAUREN (CHELSEACBOOT)",
    brand: "",
    price: "24.00",
    images: ["/footwear/Picture48.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "",
    features: [],
  },
  {
    id: "7",
    img: "/footwear/Picture49.png",
    name: "LAST-LAUREN ",
    brand: "",
    price: "27.00",
    images: ["/footwear/Picture49.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "",
    features: [],
  },
  {
    id: "8",
    img: "/footwear/Picture50.png",
    name: "HAIR ON STUD BOOT ",
    brand: "",
    price: "27.00",
    images: ["/footwear/Picture50.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "",
    features: [],
  },
  {
    id: "9",
    img: "/footwear/Picture51.png",
    name: "LAST WENDIE (CHELSEA) ",
    brand: "",
    price: "25.00",
    images: ["/footwear/Picture51.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "",
    features: [],
  },
  {
    id: "10",
    img: "/footwear/Picture52.png",
    name: "WENDIE-CHUNKY SHOE",
    brand: "",
    price: "23.00",
    images: ["/footwear/Picture52.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "",
    features: [],
  },
  {
    id: "11",
    img: "/footwear/Picture53.png",
    name: "LAST- WENDIE (BIKER BOOT)",
    brand: "",
    price: "39.00",
    images: ["/footwear/Picture53.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "",
    features: [],
  },
  {
    id: "12",
    img: "/footwear/Picture54.png",
    name: "LAST- WENDIE (BIKER BOOT)",
    brand: "",
    price: "39.00",
    images: ["/footwear/Picture54.png", "/footwear/Picture56.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "",
    features: [],
  },
  {
    id: "13",
    img: "/footwear/Picture57.png",
    name: "LS-3323 (PLATFORM BOOT)",
    brand: "",
    price: "30.00",
    images: ["/footwear/Picture57.png", "/footwear/Picture58.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "",
    features: [],
  },
  {
    id: "14",
    img: "/footwear/Picture59.png",
    name: "LS-3333 (LOFE FOR DKNY)",
    brand: "",
    price: "24.00",
    images: [
      "/footwear/Picture59.png",
      "/footwear/Picture60.png",
      "/footwear/Picture61.png",
    ],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "",
    features: [],
  },
  {
    id: "15",
    img: "/footwear/Picture62.png",
    name: "LS-3330 PRODUEFOUTBACK DKN",
    brand: "",
    price: "28.00",
    images: [
      "/footwear/Picture62.png",
      "/footwear/Picture63.png",
      "/footwear/Picture64.png",
    ],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "",
    features: [],
  },
  {
    id: "16",
    img: "/footwear/Picture65.png",
    name: "LAST-OUTBACK  ",
    brand: "",
    price: "24.00",
    images: [
      "/footwear/Picture65.png",
      "/footwear/Picture66.png",
      "/footwear/Picture67.png",
    ],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "(Best Seller 1)",
    features: [],
  },
  {
    id: "17",
    img: "/footwear/Picture68.png",
    name: "LAST-OUTBACK  ",
    brand: "",
    price: "26.00",
    images: ["/footwear/Picture68.png", "/footwear/Picture69.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "(Best Seller 2)",
    features: [],
  },
  {
    id: "18",
    img: "/footwear/Picture70.png",
    name: "LAST-OUTBACK",
    brand: "",
    price: "26.00",
    images: ["/footwear/Picture70.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "(Best Seller 3)",
    features: [],
  },
  {
    id: "19",
    img: "/footwear/Picture71.png",
    name: "LAST-OUTBACK",
    brand: "",
    price: "26.50",
    images: ["/footwear/Picture71.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "",
    features: [],
  },
  {
    id: "20",
    img: "/footwear/Picture72.png",
    name: "LAST-MOON (STUD AND BUCKLE)",
    brand: "",
    price: "25.00",
    images: ["/footwear/Picture72.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "",
    features: [],
  },
  {
    id: "21",
    img: "/footwear/Picture73.png",
    name: "CHELSEAS",
    brand: "",
    price: "26.00",
    images: ["/footwear/Picture73.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "",
    features: [],
  },
  {
    id: "22",
    img: "/footwear/Picture74.png",
    name: "LAST-TOFU (BOOT FOR STEVE MADDEN) ",
    brand: "",
    price: "26.00",
    images: ["/footwear/Picture74.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "(Lightning Chelsea)",
    features: [],
  },
  {
    id: "23",
    img: "/footwear/Picture75.png",
    name: "LAST-LUNA ",
    brand: "",
    price: "24.00",
    images: ["/footwear/Picture75.png", "/footwear/Picture76.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "(BUCKLE UP BIKER BOOTIE)",
    features: [],
  },
  {
    id: "24",
    img: "/footwear/Picture77.png",
    name: "LAST-ELECTRIC ",
    brand: "",
    price: "25.00",
    images: ["/footwear/Picture77.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "(STUDDED BOOTIE)",
    features: [],
  },
  {
    id: "25",
    img: "/footwear/Picture78.png",
    name: "LAST-ELECTRIC",
    brand: "",
    price: "26.00",
    images: ["/footwear/Picture78.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "",
    features: [],
  },
  {
    id: "26",
    img: "/footwear/Picture79.png",
    name: "LS 1857",
    brand: "",
    price: "27.00",
    images: ["/footwear/Picture79.png", "/footwear/Picture80.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "",
    features: [],
  },
  {
    id: "27",
    img: "/footwear/Picture79.png",
    name: "LS 1857",
    brand: "",
    price: "27.00",
    images: ["/footwear/Picture79.png", "/footwear/Picture80.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "",
    features: [],
  },
  {
    id: "28",
    img: "/footwear/Picture81.png",
    name: "LS 1858 - FOR DOCKERS",
    brand: "",
    price: "30.00",
    images: ["/footwear/Picture81.png", "/footwear/Picture82.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "",
    features: [],
  },
  {
    id: "29",
    img: "/footwear/Picture83.png",
    name: "LS 1861",
    brand: "",
    price: "27.00",
    images: ["/footwear/Picture83.png", "/footwear/Picture84.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "",
    features: [],
  },
  {
    id: "30",
    img: "/footwear/Picture85.png",
    name: "LS 1929",
    brand: "",
    price: "35.00",
    images: ["/footwear/Picture85.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "",
    features: [],
  },
  {
    id: "31",
    img: "/footwear/Picture86.png",
    name: "LS 1938",
    brand: "",
    price: "26.00",
    images: [
      "/footwear/Picture86.png",
      "/footwear/Picture87.png",
      "/footwear/Picture88.png",
    ],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "",
    features: [],
  },
  {
    id: "32",
    img: "/footwear/Picture89.png",
    name: "LS 1862 (LAST-TOFU)",
    brand: "",
    price: "26.00",
    images: ["/footwear/Picture89.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "",
    features: [],
  },
  {
    id: "33",
    img: "/footwear/Picture90.png",
    name: "LS 1859",
    brand: "",
    price: "27.00",
    images: ["/footwear/Picture90.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "",
    features: [],
  },
  {
    id: "34",
    img: "/footwear/Picture91.png",
    name: "LS 1928 (LAST-SAM)",
    brand: "",
    price: "24.00",
    images: ["/footwear/Picture91.png", "/footwear/Picture92.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "",
    features: [],
  },
  {
    id: "35",
    img: "/footwear/Picture93.png",
    name: "LAST-SAM (STUDDED CHELSEA)",
    brand: "",
    price: "25.00",
    images: ["/footwear/Picture93.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "",
    features: [],
  },
  {
    id: "36",
    img: "/footwear/Picture94.png",
    name: "LAST-NL (TIMBERLAND CUT)",
    brand: "",
    price: "24.00",
    images: ["/footwear/Picture94.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "",
    features: [],
  },
  {
    id: "37",
    img: "/footwear/Picture95.png",
    name: "LAST-HARLEY (LACE UP)",
    brand: "",
    price: "26.00",
    images: ["/footwear/Picture95.png"],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description: "",
    features: [],
  },
];

export const furnitureProducts: Product[] = [
  {
    id: "1",
    img: "/furniture/Picture10.png",
    name: "White Sofa",
    brand: "Al Karam",
    price: "95.5",
    images: [
      "/furniture/Picture10.png",
      "/furniture/Picture11.png",
      "/furniture/Picture12.png",
    ],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description:
      "Embrace your love for cats and sweet treats with the Cat Taiyaki Tee! This fun and quirky T-shirt features an adorable design of a playful cat enjoying a taiyaki, the iconic fish-shaped Japanese dessert. Made from premium-quality cotton, it offers a soft, breathable, and comfortable fit perfect for everyday wear.",
    features: [
      "Material: 100% high-quality cotton",
      "Fit: Relaxed and unisex sizing",
      "Design: Durable, fade-resistant cat and taiyaki graphic",
      "Perfect for casual outings, cozy days, or gifting to fellow cat enthusiasts",
    ],
  },
  {
    id: "2",
    img: "/furniture/Picture11.png",
    name: "Chair",
    brand: "Al Karam",
    price: "95.5",
    images: [
      "/furniture/Picture10.png",
      "/furniture/Picture11.png",
      "/furniture/Picture12.png",
    ],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description:
      "Embrace your love for cats and sweet treats with the Cat Taiyaki Tee! This fun and quirky T-shirt features an adorable design of a playful cat enjoying a taiyaki, the iconic fish-shaped Japanese dessert. Made from premium-quality cotton, it offers a soft, breathable, and comfortable fit perfect for everyday wear.",
    features: [
      "Material: 100% high-quality cotton",
      "Fit: Relaxed and unisex sizing",
      "Design: Durable, fade-resistant cat and taiyaki graphic",
      "Perfect for casual outings, cozy days, or gifting to fellow cat enthusiasts",
    ],
  },
  {
    id: "3",
    img: "/furniture/Picture12.png",
    name: "Chair",
    brand: "Al Karam",
    price: "95.5",
    images: [
      "/furniture/Picture10.png",
      "/furniture/Picture11.png",
      "/furniture/Picture12.png",
    ],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description:
      "Embrace your love for cats and sweet treats with the Cat Taiyaki Tee! This fun and quirky T-shirt features an adorable design of a playful cat enjoying a taiyaki, the iconic fish-shaped Japanese dessert. Made from premium-quality cotton, it offers a soft, breathable, and comfortable fit perfect for everyday wear.",
    features: [
      "Material: 100% high-quality cotton",
      "Fit: Relaxed and unisex sizing",
      "Design: Durable, fade-resistant cat and taiyaki graphic",
      "Perfect for casual outings, cozy days, or gifting to fellow cat enthusiasts",
    ],
  },
  {
    id: "4",
    img: "/furniture/Picture11.png",
    name: "Chair",
    brand: "Al Karam",
    price: "95.5",
    images: [
      "/furniture/Picture10.png",
      "/furniture/Picture11.png",
      "/furniture/Picture12.png",
    ],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description:
      "Embrace your love for cats and sweet treats with the Cat Taiyaki Tee! This fun and quirky T-shirt features an adorable design of a playful cat enjoying a taiyaki, the iconic fish-shaped Japanese dessert. Made from premium-quality cotton, it offers a soft, breathable, and comfortable fit perfect for everyday wear.",
    features: [
      "Material: 100% high-quality cotton",
      "Fit: Relaxed and unisex sizing",
      "Design: Durable, fade-resistant cat and taiyaki graphic",
      "Perfect for casual outings, cozy days, or gifting to fellow cat enthusiasts",
    ],
  },
  {
    id: "5",
    img: "/furniture/Picture12.png",
    name: "Chair",
    brand: "Al Karam",
    price: "95.5",
    images: [
      "/furniture/Picture10.png",
      "/furniture/Picture11.png",
      "/furniture/Picture12.png",
    ],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description:
      "Embrace your love for cats and sweet treats with the Cat Taiyaki Tee! This fun and quirky T-shirt features an adorable design of a playful cat enjoying a taiyaki, the iconic fish-shaped Japanese dessert. Made from premium-quality cotton, it offers a soft, breathable, and comfortable fit perfect for everyday wear.",
    features: [
      "Material: 100% high-quality cotton",
      "Fit: Relaxed and unisex sizing",
      "Design: Durable, fade-resistant cat and taiyaki graphic",
      "Perfect for casual outings, cozy days, or gifting to fellow cat enthusiasts",
    ],
  },
  {
    id: "6",
    img: "/furniture/Picture13.png",
    name: "Chair",
    brand: "Al Karam",
    price: "95.5",
    images: [
      "/furniture/Picture10.png",
      "/furniture/Picture11.png",
      "/furniture/Picture12.png",
    ],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description:
      "Embrace your love for cats and sweet treats with the Cat Taiyaki Tee! This fun and quirky T-shirt features an adorable design of a playful cat enjoying a taiyaki, the iconic fish-shaped Japanese dessert. Made from premium-quality cotton, it offers a soft, breathable, and comfortable fit perfect for everyday wear.",
    features: [
      "Material: 100% high-quality cotton",
      "Fit: Relaxed and unisex sizing",
      "Design: Durable, fade-resistant cat and taiyaki graphic",
      "Perfect for casual outings, cozy days, or gifting to fellow cat enthusiasts",
    ],
  },
  {
    id: "7",
    img: "/furniture/Picture14.png",
    name: "Chair",
    brand: "Al Karam",
    price: "95.5",
    images: [
      "/furniture/Picture10.png",
      "/furniture/Picture11.png",
      "/furniture/Picture12.png",
    ],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description:
      "Embrace your love for cats and sweet treats with the Cat Taiyaki Tee! This fun and quirky T-shirt features an adorable design of a playful cat enjoying a taiyaki, the iconic fish-shaped Japanese dessert. Made from premium-quality cotton, it offers a soft, breathable, and comfortable fit perfect for everyday wear.",
    features: [
      "Material: 100% high-quality cotton",
      "Fit: Relaxed and unisex sizing",
      "Design: Durable, fade-resistant cat and taiyaki graphic",
      "Perfect for casual outings, cozy days, or gifting to fellow cat enthusiasts",
    ],
  },
  {
    id: "8",
    img: "/furniture/Picture15.png",
    name: "Chair",
    brand: "Al Karam",
    price: "95.5",
    images: [
      "/furniture/Picture10.png",
      "/furniture/Picture11.png",
      "/furniture/Picture12.png",
    ],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description:
      "Embrace your love for cats and sweet treats with the Cat Taiyaki Tee! This fun and quirky T-shirt features an adorable design of a playful cat enjoying a taiyaki, the iconic fish-shaped Japanese dessert. Made from premium-quality cotton, it offers a soft, breathable, and comfortable fit perfect for everyday wear.",
    features: [
      "Material: 100% high-quality cotton",
      "Fit: Relaxed and unisex sizing",
      "Design: Durable, fade-resistant cat and taiyaki graphic",
      "Perfect for casual outings, cozy days, or gifting to fellow cat enthusiasts",
    ],
  },
  {
    id: "9",
    img: "/furniture/Picture16.png",
    name: "Chair",
    brand: "Al Karam",
    price: "95.5",
    images: [
      "/furniture/Picture10.png",
      "/furniture/Picture11.png",
      "/furniture/Picture12.png",
    ],
    sales: 10402,
    reviewsCount: 1243,
    rating: 4.1,
    description:
      "Embrace your love for cats and sweet treats with the Cat Taiyaki Tee! This fun and quirky T-shirt features an adorable design of a playful cat enjoying a taiyaki, the iconic fish-shaped Japanese dessert. Made from premium-quality cotton, it offers a soft, breathable, and comfortable fit perfect for everyday wear.",
    features: [
      "Material: 100% high-quality cotton",
      "Fit: Relaxed and unisex sizing",
      "Design: Durable, fade-resistant cat and taiyaki graphic",
      "Perfect for casual outings, cozy days, or gifting to fellow cat enthusiasts",
    ],
  },
];

export const productArrival: NewProduct[] = [
  {
    id: 1,
    path: "/website/footwear",
    categories: ["ALL", "FOOTWEAR"],
    img: "/footwear/Picture2.png",
    name: "Brown Shoes",
    price: "$95.50",
    reviews: "(4.1k) Customer Reviews",
    soldOutText: "Almost Sold Out",
    brand: "Al Karam",
  },
  {
    id: 2,
    path: "/website/footwear",
    categories: ["ALL", "FOOTWEAR"],
    img: "/footwear/Picture1.png",
    name: "Black Shoes",
    price: "$95.50",
    reviews: "(4.1k) Customer Reviews",
    soldOutText: "Almost Sold Out",
    brand: "Al Karam",
  },
  {
    id: 3,
    path: "/website/furniture",
    categories: ["ALL", "FURNITURE"],
    img: "/furniture/Picture2.png",
    name: "White Sofa",
    price: "$95.50",
    reviews: "(4.1k) Customer Reviews",
    soldOutText: "Almost Sold Out",
    brand: "Al Karam",
  },
  {
    id: 4,
    path: "/website/furniture",
    categories: ["ALL", "FURNITURE"],
    img: "/furniture/Picture1.png",
    name: "Chair",
    price: "$95.50",
    reviews: "(4.1k) Customer Reviews",
    soldOutText: "Almost Sold Out",
    brand: "Al Karam",
  },
  {
    id: 5,
    path: "/website/footwear",
    categories: ["FOOTWEAR"],
    img: "/footwear/Picture3.png",
    name: "Shoes",
    price: "$95.50",
    reviews: "(4.1k) Customer Reviews",
    soldOutText: "Almost Sold Out",
    brand: "Al Karam",
  },
  {
    id: 7,
    path: "/website/bag",
    categories: ["ALL", "BAG"],
    img: "/bag/Picture10.png",
    name: "Bag",
    price: "$95.50",
    reviews: "(4.1k) Customer Reviews",
    soldOutText: "Almost Sold Out",
    brand: "Al Karam",
  },
  {
    id: 8,
    path: "/website/bag",
    categories: ["ALL", "BAG"],
    img: "/bag/Picture65.png",
    name: "Bag",
    price: "$95.50",
    reviews: "(4.1k) Customer Reviews",
    soldOutText: "Almost Sold Out",
  },
  {
    id: 9,
    path: "/website/jacket",
    categories: ["ALL", "JACKET"],
    img: "/jacket/Picture62.png",
    name: "Jacket",
    price: "$95.50",
    reviews: "(4.1k) Customer Reviews",
    soldOutText: "Almost Sold Out",
    brand: "Al Karam",
  },
  {
    id: 10,
    path: "/website/jacket",
    categories: ["ALL", "JACKET"],
    img: "/jacket/Picture63.png",
    name: "Jacket",
    price: "$95.50",
    reviews: "(4.1k) Customer Reviews",
    soldOutText: "Almost Sold Out",
    brand: "Al Karam",
  },
];

export const allCollections: Record<string, Product[]> = {
  jackets: jacketProducts,
  footwear: footwearProducts,
  furniture: furnitureProducts,
  bag: bagProducts,
  menFootwear: menFootwearProducts,
  womenFootwear: womenFootwearProducts,
};
